### ISSUE TITLE
redirect_uri uses local loopback - 127.0.0.1

### ISSUE THREAD

**Issue by vidarkongsli** [pawelniewie/social-authentication-for-atlassian#13]
I have tried to configure and Oidc/Oauth2 provider, but when the plugin sends the user to the idp, it gets the &redirect_uri wrong: 

<img width="571" alt="localhost_redirect_uri" src="https://cloud.githubusercontent.com/assets/67829/24105914/b2a0c308-0d86-11e7-97b7-34e946b6a209.PNG">
<img width="439" alt="callback_setting" src="https://cloud.githubusercontent.com/assets/67829/24105915/b58efd50-0d86-11e7-8b15-e7b1a4c4fb5b.PNG">

What could be the cause of this?

Thank you

**Comment by vidarkongsli** [comment]
Confluence version 5.10.8, plugin version 3.1.0

**Comment by pawelniewie** [comment]
Thank you for reporting this! I already located where there problem is and will issue an update later today.

**Comment by pawelniewie** [comment]
Can you verify this version works for you - https://www.dropbox.com/s/21vl4cmtbbc00zb/confluence-openid-authentication-plugin-3.1.2-SNAPSHOT.jar?dl=0

**Comment by vidarkongsli** [comment]
Excellent, the fix seems to work. Thank you!

**Comment by pawelniewie** [comment]
Fixed in 3.1.2
