### ISSUE TITLE
Plugin only valid to 443 default port

### ISSUE THREAD

**Issue by is44c** [pawelniewie/social-authentication-for-atlassian#2]
For security reasons we have our provider behind another port (8443) If you try to add the port to url you get an error:

There was a SSL error when connecting to the provider: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

When the connection was correctly tested to another port with SSLPoke provide by Atlassian:

[root@almsvr05 ~]# java SSLPoke ourxxxid.xxx.any 8443
Successfully connected

In fact if you add the URL without port you get a discovery document missing:

OpenId Connect discovery document at https://ourxxxid.xxx.any is invalid or missing.

Either url parsing adding port or a field for configuration should be added to Add-on configuration for OpenID/OAuth 2.0.

**Comment by pawelniewie** [comment]
Let me guess you have a self signed certificate there? Or one that is not supported by your JVM.

The error message you got "unable to find valid certification path to requested target" suggests that there is a missing CA certificate in your JVM running JIRA.

Here's a documentation on importing CA certificate into Java KeyStore. It is for Confluence but similar setup applies to JIRA.

**Comment by is44c** [comment]
Thank your for your guessing but it's not the case :) Certificate has been correctly added to the JVM otherwise I couldn't connect with SSLPoke class I have for testing purpose got from Atlassian as said in previous comment:

"When the connection was correctly tested to another port with SSLPoke provide by Atlassian:

[root@almsvr05 ~]# java SSLPoke ourxxxid.xxx.any 8443
Successfully connected"

Problem seen related to port in use, in the field of Provider URL if you add:

ourxxxid.xxx.any:8443

You got a SSL error because I presume parsing of port is not correct.

**Comment by pawelniewie** [comment]
Thanks for clarifying. I will look into that.
