### ISSUE TITLE
setup with GLUU IdP

### ISSUE THREAD

**Issue by mmacduff** [pawelniewie/social-authentication-for-atlassian#27]
We are attempting to point to our gluu server.  WIthin Gluu we've added an openid client with a key and callback that is from this plugin configuration.  We configured the plugin and get the button on the login page but when we click on it, it redirects to our gluu server where we get an error ""The client is not authorized to request an access token using this method.".  
This may be a matter of setting gluu to be compatible with this plugin?

**Comment by pawelniewie** [comment]
It does seem like there's more configuration required on the server (guessing from the message). I have no experience configuring it myself.

**Comment by mmacduff** [comment]
For perhaps others sake I offer the settings I needed to change to get this to work.
First of all Gluu calls the client_id an "Inum".  
The 'redirect_uris' field should be set based on this plugins value for that.
Additionally in Gluu set the following:
response_type: code
grant_type: authorization_code
scopes: openid email profile
Auth for Token Endpoint: client_secret_post

This otherwise seems to be working fine.  Thanks for a useful app.

**Comment by pawelniewie** [comment]
Thank you for sharing! 👏
