### ISSUE TITLE
Additional Log Output

### ISSUE THREAD

**Issue by asiral** [pawelniewie/social-authentication-for-atlassian#40]
I have configured OpenID on our JIRA instance and all seems to work as expected except the final step of authenticating within JIRA.  If I set the "Allowed Domains" to our domain, I get the message:

"Your email address is not on a list of allowed domains. Please use a different account to log in."

If I unset "Allowed Domains", I get the message:

"No existing user was matched. Cannot proceed. Please try again using different method."

I know my email address exists in a JIRA user account and the domain for it is correct.  How can I troubleshoot this further?  Is there any way to increase the log level?  To see the email address or domain the plug-in claims is invalid?

**Comment by pawelniewie** [comment]
Is enabling public mode in JIRA or in the plugin changes the behaviour? You can enable it right bellow list of providers.
