### ISSUE TITLE
Documentation page is down

### ISSUE THREAD

**Issue by valentijnscholten** [pawelniewie/social-authentication-for-atlassian#47]
https://docs.pawelniewiadomski.com/atlassian/google-apps-authentication-for-jira/ is throwing an error:

     404 Not Found
     Code: NoSuchKey
     Message: The specified key does not exist.
     Key: 404.html
     RequestId: 8027AA57EA17447A
     HostId: DgS4hLYg5nB+lH3jSqAHo/vHYUK56OX7YLInABvsry10dOnWEcO2vUIEgJmvq6bLvUHbcnXTj88=
     An Error Occurred While Attempting to Retrieve a Custom Error Document
     Code: NoSuchKey
     Message: The specified key does not exist.
     Key: error.html

**Comment by pawelniewie** [comment]
Thanks for reporting! I fixed links to the documentation on Marketplace.
