### ISSUE TITLE
Confluence doesn't detect that a newer plugin is available

### ISSUE THREAD

**Issue by jpnavarro** [pawelniewie/social-authentication-for-atlassian#49]
Is it expected that Confluence v5.9.12 running OpenID Authentication for Confluence v3.1.2 does not detect that a newer v3.1.7 plugin is available?

**Comment by pawelniewie** [comment]
Yes, as 3.1.7 version is marked to be compatible with Confluence >= 5.10.0. It should still work but I'm not testing it with.
