### ISSUE TITLE
Date for next Easy sign-ups for JIRA ServiceDesk version update

### ISSUE THREAD

**Issue by ssabebe** [pawelniewie/social-authentication-for-atlassian#52]
Any plans to release an updated version of Easy sign-ups for JIRA ServiceDesk that's compatible with JIRA v. 7.9.2?

**Comment by pawelniewie** [comment]
Will test it tomorrow (Friday).

**Comment by pawelniewie** [comment]
3.2.2 is compatible with 7.9.x
