### ISSUE TITLE
new users are not added to jira-users group

### ISSUE THREAD

**Issue by trevormarshall** [pawelniewie/social-authentication-for-atlassian#54]
Using GitHub auth with OpenID Authentication for Jira, JIRA 7.9 with public sign up enabled.

If a user does not exist, and they login with GitHub for the first time, they are not added to the jira-users group, and so do not have application access and cannot create bugs.
The expected behaviour would be for the user to be automatically be put into the jira-users group, similar to accounts that register with the site.

**Comment by pawelniewie** [comment]
Thanks! I will check that tomorrow.

**Comment by pawelniewie** [comment]
Released 3.2.3 with a fix for that. Thanks for reporting! :pray:
