### ISSUE TITLE
OpenID plugin fail for Administrator Access

### ISSUE THREAD

**Issue by crackmac** [pawelniewie/social-authentication-for-atlassian#57]
After logging in with OpenID user that belongs to jira-administrator group we are unable to access Jira Administration features. We trying to access an administration function we are asked to validate credentials again and that is where login fails (see attached screen shot).
![open-id-plugin-admin-fail](https://user-images.githubusercontent.com/335272/43229911-3b251432-901b-11e8-8fd4-068a16c6f42e.jpg)

**Comment by pawelniewie** [comment]
Yes, that's a known issue, the only workaround is to disable websudo in Jira but this is not recommended by me. For admins I suggest using a password manager instead.
