### ISSUE TITLE
Google OAuth 2.0 disallowed_useragent

### ISSUE THREAD

**Issue by fxkai** [pawelniewie/social-authentication-for-atlassian#59]
Using the OpenID Plugin with Google and the Confluence Server App leads to an Error 403 disallowed_useragent as referred here : https://auth0.com/blog/google-blocks-oauth-requests-from-embedded-browsers/

Is there a way to manually set the useragent such as in example here : https://github.com/RocketChat/Rocket.Chat.Cordova/issues/159

**Comment by pawelniewie** [comment]
There isn't a way as the request is performed by the built in web view. This renders the plugin unusable for mobile Confluence app. No workaround exists.
