### ISSUE TITLE
Google+ APIs being shutdown

### ISSUE THREAD

**Issue by srijan** [pawelniewie/social-authentication-for-atlassian#62]
I got an email from Google that Google+ APIs are shutting down soon.

From https://developers.google.com/+/api-shutdown:
> On March 7, 2019, all Google+ APIs will be shut down. This will be a progressive shutdown beginning in late January, with calls to these APIs starting to intermittently **fail as early as January 28, 2019**.

> The Google+ Sign-in feature has been fully deprecated and will also be shut down on March 7, 2019. Developers should migrate to the more comprehensive [Google Sign-in](https://developers.google.com/identity/) authentication system.

I can see Google+ APIs being used in two places:
https://github.com/pawelniewie/social-authentication-for-atlassian/search?q=googleapis.com&unscoped_q=googleapis.com

**Comment by jmorasld** [comment]
Hi @pawelniewie ,

We've the same doubt as @edsonschleiwabion, will we have a solution before March?

Thanks!

Regards,
Jorge

**Comment by pawelniewie** [comment]
Released `3.2.4` which uses Google Sign In API, no migration is needed.

**Comment by anderbarbier** [comment]
It works!
Thank you
