### ISSUE TITLE
Support for Jira 8.0.1

### ISSUE THREAD

**Issue by malbiez** [pawelniewie/social-authentication-for-atlassian#68]
We are trying to use the plugin with Jira 8.0.1. Since our Jira is not connected to the Internet, we tried uploading it to the UPM via the web interface, which failed. Copying the plugin into `/var/lib/jira/plugins/installed-plugins' did show the plugin in the Jira UI, however, enabling it caused a `An unexpected error occurred. Refer to the logs for more information.` without any real hint in the logs.

Help would be greatly appreciated :)

**Comment by edsonschleiwabion** [comment]
Hi there,

I got the followin error in the logs (/opt/atlassian/jira/logs/catalina.out), and the Manager Apps interface show that it is incompactible with the version 8.0.1.

___ FAILED PLUGIN REPORT _____________________
    
    1 plugin failed to load during JIRA startup.
    
        'com.pawelniewiadomski.jira.jira-openid-authentication-plugin' - 'OpenID Authentication for JIRA'  failed to load.
                Cannot start plugin: com.pawelniewiadomski.jira.jira-openid-authentication-plugin
                        Unable to resolve com.pawelniewiadomski.jira.openid-authentication-plugin [184](R 184.0): missing requirement [com.pawelniewiadomski.jira.openid-authentication-plugin [184](R 184.
0)] osgi.wiring.package; (&(osgi.wiring.package=com.atlassian.sal.api)(version>=2.10.0)(!(version>=4.0.0))) Unresolved requirements: [[com.pawelniewiadomski.jira.openid-authentication-plugin [184](R 184.
0)] osgi.wiring.package; (&(osgi.wiring.package=com.atlassian.sal.api)(version>=2.10.0)(!(version>=4.0.0)))]
    
                It was loaded from /var/atlassian/application-data/jira/plugins/installed-plugins/plugin.5581287077643731251.jira-openid-authentication-plugin-3.2.4.jar

**Comment by tdefigueiredo** [comment]
Hi! Are there plans to have open ID authentication compatible for JIRA 8.0.1?

**Comment by pawelniewie** [comment]
I released a new version that works with Jira 8.x
