### ISSUE TITLE
Authentication problem using Azure Oauth2

### ISSUE THREAD

**Issue by Ralph-Zitz** [pawelniewie/social-authentication-for-atlassian#69]
Hi,

We had a working authentication flow using OpenID Connect with our Azure AD setup. We changed the URL for our Jira instance, and of course updated the callback URL in our Application registration in Azure AD. Client ID and Client Secret were unchanged, but now some accounts seem to no longer be able to login. The ones that fail receive the following error:
` Login returned 'interaction_required, AADSTS530003: Your device is required to be managed to access this resource. Trace ID: 15bc3a43-8da3-45bc-a2da-1099625e4600 Correlation ID: 744fc086-26cc-4086-9022-a5fafb7e91a7 Timestamp: 2019-04-15 16:34:53Z' which suggests an invalid configuration, please check if Client ID and Client Secret match with those offered by Login.`
Could it be a cache we need to clear somewhere, or do we need to set up the plugin again now that the URL has changed?

**Comment by pawelniewie** [comment]
No idea what that could be :-(

**Comment by Ralph-Zitz** [comment]
We believe we might have tracked it down to a potential problem in the Azure AD policies, so not a problem with _this_ plugin
