### ISSUE TITLE
Session duration is too short.

### ISSUE THREAD

**Issue by YukSeungChan** [pawelniewie/social-authentication-for-atlassian#7]
I think session duration is too short. How can i increase the duration of the session?

**Comment by pawelniewie** [comment]
You cannot currently.

**Comment by kha0S** [comment]
@pawelniewie Is there anything we can change to address this? We bought the add-on for Confluence and Jira and it works really well but now I have a bunch of angry users complaining about the need to login a dozen times per day...

**Comment by pawelniewie** [comment]
Did you configure JIRA/Confluence to enable longer sessions? 

See https://confluence.atlassian.com/jira063/changing-the-default-session-timeout-683542392.html

What session-timeout do you have configured?

After what time (roughly) users are logged out?

What stack do you have - JIRA accessed directly or behind nginx/apache?

Can you check in the browser if JIRA cookie JSESSIONID has any expiration date set?

What browser your users use most of the time?

I'd love to help you with that.

**Comment by kha0S** [comment]
Thank you for the reply @pawelniewie 
I checked our configs to confirm we had 300 minutes set as our session timeout, but the value was again set to 30 minutes. My guess is that the value was reset during one of the upgrades.

- 5 hours (300 minutes)
- Will monitor during the day
- Both Jira and Confluence run behind nginx
- We have JSESSIONID set. The expiration date is set to "Session"
- The vast majority uses Google Chrome

**Comment by kha0S** [comment]
@pawelniewie After testing during the last 2 days we have a better behavior now, but the session timeouts way before the 5 hours we configured. We are getting session timeout after 1 hour without interacting with the site

**Comment by kha0S** [comment]
@pawelniewie any news on this? Anything we can try?

**Comment by pawelniewie** [comment]
One person reported their JIRA having session-timeout set to 43200 and that giving them couple of days to a week expiration.

**Comment by kha0S** [comment]
I did precisely that yesterday. I bumped the value to 86400 and so far it's behaving much better.

**Comment by EricReiche** [comment]
While this improves the situation a bit, the following is reproducable:
- Log in via Azure
- Open some ticket
- Close browser
- Reopen browser
- Try to re-open ticket
-  Getting asked to log in

So while the session lasts longer, the login still doesn't persist between closing the browser.

**Comment by kha0S** [comment]
I can confirm that this **doesn't** fix the problem.
The behaviour is pretty much the same. Some users can work for a few hours without problems, others have their sessions terminated in less than 1 hour... 
 Suggestions welcome...

**Comment by pawelniewie** [comment]
To fix this plugin from version 3.1.0 will issue remember me token using JIRA mechanism (the same as you'd click "Remember me" on the login page).
