### ISSUE TITLE
Support for Jira 8.3.1

### ISSUE THREAD

**Issue by edsonschleiwabion** [pawelniewie/social-authentication-for-atlassian#70]
Hello @pawelniewie ,

The current version doesn't support the jira 8.3.1 version.
Do you have date for an update?

Kind regards,
Edson Schlei

**Comment by Ralph-Zitz** [comment]
Hi, this is just a +1 on the same topic (Jira 8.3.2 has now been released).

**Comment by Ralph-Zitz** [comment]
Any news on this?

**Comment by pawelniewie** [comment]
Yup, marked existing version as compatible.
